
<script language="JavaScript">
<!--
function MM_popupMsg(msg) { //v1.0
  alert(msg);
}
//-->
</script>
<table cellspacing="0" cellpadding="1" bordercolor="#FFFFFF" width="100%" border="1" bgcolor="#FFFFFF">
  <tr> 
    <td width="25%" valign="top" bgcolor="#FFFFFF" class="body_10">&nbsp; </td>
    <td colspan="3" valign="bottom" class="body_10" align="right"> <font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1"><b><font color="#003399">PVP 
      </font></b><font color="#003399">en {{moneda_text}} por a&ntilde;o</font><b><font color="#003399"> 
      </font></b></font><font color="#003399" face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>(<a href="#" onClick="MM_popupMsg('A los titulares de dominios residentes en Espa&ntilde;a se les gravar&aacute; \run 21% de IVA adicional al final del proceso de registro. ')">SIN 
      IVA</a>) </b></font></td>
  </tr>
  <tr> 
    <td bgcolor="#003399" width="25%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>D 
        O M I N I O</b></font></div>
    </td>
    <td bgcolor="#003399" width="25%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1">1 
        a&ntilde;o</font></div>
    </td>
    <td bgcolor="#003399" width="23%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1"> 
        2 a 4 a&ntilde;os</font></div>
    </td>
    <td bgcolor="#003399" width="27%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1">5 
        o m&aacute;s </font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b> 
        .com .net .org</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="25%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-com_pvp_1}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="23%" class="td_form_valor2" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-com_pvp_2}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="27%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-com_pvp_3}}</b></font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>.es</b></font></div>
    </td>
    <td bgcolor="#FFFF99" height="20" width="25%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-es_pvp_1}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" height="20" width="23%" class="td_form_valor2" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>n/a</b></font></div>
    </td>
    <td bgcolor="#FFFF99" height="20" width="27%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>n/a</b></font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>.tv</b></font></div>
    </td>
    <td bgcolor="#FFFF99" height="20" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-tv_pvp_1}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" height="20" class="td_form_valor2" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-tv_pvp_2}}</b></font></td>
    <td bgcolor="#FFFF99" height="20" class="td_form_valor" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-tv_pvp_1}}</b></font></td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>.cc</b></font></td>
    <td bgcolor="#FFFF99" height="20" class="td_form_valor" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-cc_pvp_1}}</b></font></td>
    <td bgcolor="#FFFF99" height="20" class="td_form_valor2" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-cc_pvp_2}}</b></font></td>
    <td bgcolor="#FFFF99" height="20" class="td_form_valor" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-cc_pvp_3}} 
      </b></font></td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>.info</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="25%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-info_pvp_1}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="23%" class="td_form_valor2" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-info_pvp_2}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="27%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-info_pvp_3}}</b></font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>.biz</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="25%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-biz_pvp_1}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="23%" class="td_form_valor2" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-biz_pvp_2}}</b></font></div>
    </td>
    <td bgcolor="#FFFF99" width="27%" class="td_form_valor" align="center"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>{{estandar-biz_pvp_3}}</b></font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>.name</b></font></td>
    <td height="20" colspan="3" class="td_form_valor" align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="1" color="#666666"><b>proximamente</b></font></td>
  </tr>
  <tr align="right"> 
    <td bgcolor="#FFFFFF" colspan="4"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><img src="imagenes/spacer.gif" width="5" height="5"></font></td>
  </tr>
  <tr align="right" valign="bottom"> 
    <td bgcolor="#FFFFFF" colspan="4"> <font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1"><b><font color="#003399">PVP 
      ADICIONAL </font></b><font color="#003399">en {{moneda_text}} por a&ntilde;o</font><b><font color="#003399"> 
      </font></b></font><font color="#003399" face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>(<a href="#" onClick="MM_popupMsg('A los titulares de dominios residentes en Espa&ntilde;a se les gravar&aacute; \run 21% de IVA adicional al final del proceso de registro. ')">SIN 
      IVA</a>) </b></font></td>
  </tr>
  <tr> 
    <td bgcolor="#003399" width="25%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>O 
        P C I O N E S</b></font></div>
    </td>
    <td bgcolor="#003399" width="25%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1">1 
        a&ntilde;o</font></div>
    </td>
    <td bgcolor="#003399" width="23%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1"> 
        2 a 4 a&ntilde;os</font></div>
    </td>
    <td bgcolor="#003399" width="27%" class="body_10"> 
      <div align="center"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif" size="1">5 
        o m&aacute;s </font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center" height="18"> 
      <font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b> OPCI&Oacute;N 
      PRO&nbsp;</b></font></td>
    <td bgcolor="#FFFF99" width="25%" class="td_form_valor" height="18"> 
      <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="1">+{{pro2_pvp_1}}</font></b></div>
    </td>
    <td bgcolor="#FFFF99" width="23%" class="td_form_valor2" height="18"> 
      <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="1">+{{pro2_pvp_2}}</font></b></div>
    </td>
    <td bgcolor="#FFFF99" width="27%" class="td_form_valor" height="18"> 
      <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="1">+{{pro2_pvp_3}}</font></b></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF" width="25%" class="td_form_titulo" align="center"> <font face="Verdana, Arial, Helvetica, sans-serif" size="1"><b>DNS 
      AVANZADA&nbsp;</b></font></td>
    <td bgcolor="#FFFF99" width="25%" class="td_form_valor" height="18"> 
      <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="1">+{{pro3_pvp_1}}</font></b></div>
    </td>
    <td bgcolor="#FFFF99" width="23%" class="td_form_valor2" height="18"> 
      <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="1">+{{pro3_pvp_2}}</font></b></div>
    </td>
    <td bgcolor="#FFFF99" width="27%" class="td_form_valor" height="18"> 
      <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="1">+{{pro3_pvp_3}}</font></b></div>
    </td>
  </tr>
  <tr align="left"> 
    <td colspan="4" class="mini">&nbsp;</td>
  </tr>
  <tr align="left"> 
    <td colspan="4" class="mini">* <font color="#FF0000">NOTA DOMINIOS .ES</font>: 
      En el precio de los dominios <b>&quot;.es&quot;</b> (ESNIC) <b>NO ESTA INCLUIDA</b> 
      la cuota de registro del ESNIC que se pagar&aacute; mediante factura emitida 
      por el propio organismo al contacto de facturaci&oacute;n del registro. 
      Los precios a Diciembre de 2001 son: Primer a&ntilde;o: <b>72,12 &euro;</b>, 
      siguientes: <b>48,08 &euro;</b>. Pagadero por a&ntilde;os &quot;naturales&quot; 
      de Enero a Diciembre, indistintamente del momento del registro. </td>
  </tr>
  <tr align="center"> 
    <td colspan="4" bgcolor="#FFFFFF" height="43"><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><br>
      <a href="{{CGI}}"><img src="/imagenes/botones_convert_{{convert}}.gif" border="0"></a></font></td>
  </tr>
</table>
