            <p><b><font color="#CC0000" size="2">Servicios no contratados</font>.</b><br>
              <font size="1">Para usar la gesti&oacute;n de zonas, el dominio
              debe haberse sido registrado con nuestra opcion &quot;PRO&quot;.
              Su dominio no figura en nuestro registros con esta opci&oacute;n
              por lo que estos servicios no est&aacute;n disponibles. Para cualquier
              consulta puede enviar un email al <a href="mailto:registros@alsur.es" onMouseOver="window.status='registros@nombremania.com';return true" onMouseOut="window.status='';return true">Dpto.
              Registros.</a></font></p>
